Better error handling.

diff --git a/bin/gpml2 b/bin/gpml2
--- a/bin/gpml2
+++ b/bin/gpml2
@@ -9,23 +9,37 @@ cleanup() {
   echo "done" > /dev/null
 }
 
-# drawing on https://codeinthehole.com/tips/bash-error-reporting/
-function handle_error {
-  read line file <<<$(caller)
-  echo "An error occurred in line $line of file $file:" >&2
-  sed "${line}q;d" "$file" >&2
+# Based on http://linuxcommand.org/lc3_wss0140.php
+# and https://codeinthehole.com/tips/bash-error-reporting/
+PROGNAME=$(basename $0)
+error_exit() {
+#	----------------------------------------------------------------
+#	Function for exit due to fatal program error
+#		Accepts 1 argument:
+#			string containing descriptive error message
+#	----------------------------------------------------------------
+
+
+  #echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  if [ ! "$1" ]; then
+    echo "${PROGNAME}: Unknown Error" 1>&2
+    read line file <<<$(caller)
+    echo "An error occurred in line $line of file $file:" 1>&2
+    sed "${line}q;d" "$file" 1>&2
+  else
+    echo "${PROGNAME}: $1" 1>&2
+  fi
+
   cleanup
   exit 1
 }
 
-trap handle_error ERR
+trap error_exit ERR
 trap cleanup EXIT INT QUIT TERM
 
 TOP_OPTS=$(getopt -o hv: --long help,version:,id:,pathway-version: \
              -n 'gpml2' -- "$@")
-
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
-
+if [ $? != 0 ] ; then error_exit "Error: Failed to parse options." ; fi
 # NOTE: keep the quotes
 eval set -- "$TOP_OPTS"
 
@@ -45,7 +59,7 @@ while true; do
 done
 
 if [ $VERSION == true ]; then
-  # TODO
+  # TODO: this is not a real version
   echo "1.0.0"
   exit 0
 elif [ $HELP == true ]; then
@@ -63,8 +77,7 @@ path_in="$1"
 path_out="$2"
 
 if [ ! -f "$path_in" ]; then
-  echo "Missing file \""$path_in"\"" >&2
-  exit 1
+  error_exit "Missing file '"$path_in"'"
 fi
 
 dir_in=$(dirname "$path_in")
@@ -85,7 +98,30 @@ fi
 if [ -z "$path_out" ]; then
   for format in json owl pdf png pwf react.svg svg txt; do
     out_f="$dir_in/$stub_in.$format"
-    "$SCRIPT_DIR/gpml2" --id "$ID" --pathway-version "$PATHWAY_VERSION" "$path_in" "$out_f"
+    #"$SCRIPT_DIR/gpml2" --id "$ID" --pathway-version "$PATHWAY_VERSION" "$path_in" "$out_f";
+
+    #"$SCRIPT_DIR/gpml2" --id "$ID" --pathway-version "$PATHWAY_VERSION" "$path_in" "$out_f" || exit 1;
+
+    if ! "$SCRIPT_DIR/gpml2" --id "$ID" --pathway-version "$PATHWAY_VERSION" "$path_in" "$out_f" ; then
+      echo "  Failed to complete the following conversion:" 1>&2;
+      echo "    $SCRIPT_DIR/gpml2 \\" 1>&2;
+      echo "    --id $ID \\" 1>&2;
+      echo "    --pathway-version $PATHWAY_VERSION \\" 1>&2;
+      echo "    $path_in \\" 1>&2;
+      echo "    $path_in" 1>&2;
+      exit 1;
+    fi
+
+    #"$SCRIPT_DIR/gpml2" --id "$ID" --pathway-version "$PATHWAY_VERSION" "$path_in" "$out_f" || \
+    #  (echo "Error: $SCRIPT_DIR/gpml2 --id $ID --pathway-version $PATHWAY_VERSION $path_in $out_f" 1>&2; \
+	#exit 1)
+
+    #"$SCRIPT_DIR/gpml2" --id "$ID" --pathway-version "$PATHWAY_VERSION" "$path_in" "$out_f" || \
+    # (echo "Error: $SCRIPT_DIR/gpml2 --id $ID --pathway-version $PATHWAY_VERSION $path_in $out_f"; \
+	#exit 1)
+
+    #"$SCRIPT_DIR/gpml2" --id "$ID" --pathway-version "$PATHWAY_VERSION" "$path_in" "$out_f" || \
+    #  error_exit "Error: $SCRIPT_DIR/gpml2 --id $ID --pathway-version $PATHWAY_VERSION $path_in $out_f" ;
   done
   exit 0
 fi
@@ -99,10 +135,19 @@ stub_out="${base_out%.*}"
 xmlstarlet='/nix/store/dwigzvk3yrbai9mxh3k2maqsghfjqgr6-xmlstarlet-1.6.1/bin/xmlstarlet'
 
 gpml_f="$dir_in/$stub_in.gpml"
+
+# TODO: which is better?
+#$xmlstarlet val "$f";
+#if [ $? -eq 0 ]; then ... fi
+is_valid=$(($xmlstarlet val "$gpml_f" | grep ' valid') || echo '');
+if [ ! "$is_valid" ]; then
+  error_exit "Error: Invalid GPML for $gpml_f"
+fi
+
 ns=$($xmlstarlet sel -t -v "//namespace::*[name()='']" "$gpml_f" | head -n 1)
 gpml_version="${ns##*/}"
 if [ -z "$gpml_version" ]; then
-  exit 1
+  error_exit "Error: GPML namespace missing. Expecting '$LATEST_GPML_VERSION'"
 elif [ "$gpml_version" != "$LATEST_GPML_VERSION" ]; then
   old_f="$dir_in/$stub_in.$gpml_version.gpml"
   mv "$gpml_f" "$old_f"
@@ -155,8 +200,7 @@ elif [[ "$ext_out" =~ ^(svg)$ ]]; then
       > "$dark_f"
   fi
 else
-  echo "Invalid output extension: \"$ext_out\"" >&2
-  exit 1
+  error_exit "Invalid output extension: '$ext_out'"
 fi
 
 exit 0
